webtalk_init -webtalk_dir C:/Users/D-105/1104_BCD/1104_BCD.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov  4 17:38:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a06c293f-c428-4d23-af5b-ecdd1b4e98a3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bfd65c3d-2e25-4f34-8c8d-b369e4bc40af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13632093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "03:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-SMT2/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-SMT2/15000000:Digilent/JTAG-SMT2/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-SMT2/15000000:Digilent/JTAG-SMT2/15000000:Digilent/JTAG-SMT2/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 3013201119 -regid "" -xml C:/Users/D-105/1104_BCD/1104_BCD.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/D-105/1104_BCD/1104_BCD.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/D-105/1104_BCD/1104_BCD.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
