set_property PACKAGE_PIN F16 [get_ports {Q[3]}]
set_property PACKAGE_PIN F14 [get_ports {Q[2]}]
set_property PACKAGE_PIN F13 [get_ports {Q[1]}]
set_property PACKAGE_PIN F15 [get_ports {Q[0]}]
set_property PACKAGE_PIN D20 [get_ports {seg[6]}]
set_property PACKAGE_PIN C20 [get_ports {seg[5]}]
set_property PACKAGE_PIN C22 [get_ports {seg[4]}]
set_property PACKAGE_PIN B22 [get_ports {seg[3]}]
set_property PACKAGE_PIN B21 [get_ports {seg[2]}]
set_property PACKAGE_PIN A21 [get_ports {seg[1]}]
set_property PACKAGE_PIN E22 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[0]}]
set_property PACKAGE_PIN L3 [get_ports clk]
set_property PACKAGE_PIN J4 [get_ports clr]
set_property PACKAGE_PIN K3 [get_ports up]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clr]
set_property IOSTANDARD LVCMOS18 [get_ports up]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets Q[0]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets Q[1]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets Q[2]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets Q[3]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[0]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[1]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[2]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[3]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[4]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[5]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets seg[6]_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets a_OBUF]




set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property PACKAGE_PIN E14 [get_ports a]
set_property IOSTANDARD LVCMOS18 [get_ports a]
